"use client";

export default function HomePage() {
  function goSignup() { window.location.href = "/signup"; }
  function goLogin() { window.location.href = "/login"; }
  function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

  const industries = [
    ["🍽", "RESTAURANTS"], ["🛍", "RETAIL"], ["🏠", "HOME SERVICES"],
    ["❤", "HEALTH & WELLNESS"], ["🚗", "AUTOMOTIVE"], ["💼", "PROFESSIONAL SERVICES"],
    ["✂", "BEAUTY & SALON"], ["🏋", "FITNESS"], ["•••", "& MORE"],
  ];

  const features = [
    ["MARKETING THAT WORKS", "Done-for-you campaigns that attract, engage, and convert more customers."],
    ["REPUTATION & REVIEWS", "Get more 5-star reviews and build trust that brings in new business."],
    ["MESSAGING & LEADS", "Never miss a lead again with customer capture, follow-up, and direct communication."],
    ["APPOINTMENTS & FOLLOW UP", "Turn interest into action with better follow-up and easier scheduling."],
    ["ANALYTICS & REPORTING", "See what is working with clear performance data that helps you make better decisions."],
  ];

  const benefits = [
    "Customer growth system", "Website + lead capture", "Reviews + reputation tools", "QR code campaigns",
    "Offers + promotions", "Email + SMS campaigns", "Owner Command Center", "Dedicated Success Manager",
  ];

  return (
    <main className="page">
      <style jsx global>{`
        *{box-sizing:border-box}html,body{margin:0;padding:0;background:#050505;color:#fff;font-family:Arial,Helvetica,sans-serif}button{font:inherit}
      `}</style>
      <style jsx>{`
        .page{min-height:100vh;background:radial-gradient(circle at 83% 8%,rgba(225,34,45,.13),transparent 26%),linear-gradient(180deg,#060606,#030303)}
        .shell{width:min(1500px,calc(100% - 40px));margin:0 auto}.nav{min-height:84px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:28px;border-bottom:1px solid #1e1e1e}
        .brand{font-size:23px;font-weight:1000;letter-spacing:-1px;white-space:nowrap}.brand span{color:#e51f2b}.brand small{display:block;margin-top:2px;color:#8d8d8d;font-size:7px;letter-spacing:1.5px}
        .navLinks{display:flex;justify-content:center;gap:28px;flex-wrap:wrap}.navLinks button{padding:0;border:0;background:transparent;color:#d7d7d7;cursor:pointer;font-size:9px;font-weight:1000;letter-spacing:.7px}
        .navActions{display:flex;gap:10px}.btn{border-radius:8px;padding:13px 17px;cursor:pointer;font-size:9px;font-weight:1000;letter-spacing:.65px}.btnGhost{color:#fff;border:1px solid #333;background:#0e0e0e}.btnRed{color:#fff;border:1px solid #ed2230;background:#ed2230;box-shadow:0 13px 28px rgba(237,34,48,.18)}
        .heroWrap{border-bottom:1px solid #202020;background:linear-gradient(90deg,rgba(4,4,4,.98) 0%,rgba(4,4,4,.90) 38%,rgba(4,4,4,.38) 66%,rgba(4,4,4,.62) 100%),radial-gradient(circle at 72% 36%,rgba(181,17,28,.19),transparent 24%),linear-gradient(135deg,#090909,#15100f 65%,#080808)}
        .hero{min-height:660px;display:grid;grid-template-columns:minmax(0,.9fr) minmax(550px,1.1fr);gap:34px;align-items:center;padding:50px 0 38px}.eyebrow{color:#ee2834;font-size:10px;font-weight:1000;letter-spacing:1.8px}
        .hero h1{margin:12px 0 18px;max-width:720px;font-size:clamp(58px,6vw,92px);line-height:.93;letter-spacing:-5px;font-weight:1000}.hero h1 span{color:#ed2230}.heroLead{max-width:660px;color:#d1d1d1;font-size:17px;line-height:1.55;font-weight:700}.heroSub{max-width:650px;margin-top:10px;color:#8b8b8b;font-size:12px;line-height:1.6}.heroActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}
        .proofRow{display:flex;gap:22px;flex-wrap:wrap;margin-top:28px}.proof{display:flex;align-items:center;gap:9px;padding-right:20px;border-right:1px solid #2b2b2b;color:#b9b9b9;font-size:9px;line-height:1.35}.proof:last-child{border-right:0}.proofIcon{color:#ed2230;font-size:18px}
        .deviceStage{min-height:520px;position:relative;display:grid;place-items:center}.laptop{width:95%;min-height:445px;border:2px solid #3a3a3a;border-radius:22px;background:linear-gradient(160deg,#121212,#080808);box-shadow:0 30px 80px rgba(0,0,0,.55);padding:18px;transform:perspective(1200px) rotateY(-3deg) rotateX(1deg)}
        .screen{min-height:405px;border-radius:13px;border:1px solid #252525;background:#0a0a0a;padding:20px;overflow:hidden}.screenTop{display:flex;justify-content:space-between;align-items:center;padding-bottom:15px;border-bottom:1px solid #1f1f1f}.screenBrand{font-size:12px;font-weight:1000}.screenBrand span{color:#ed2230}.welcome{margin:16px 0 14px;font-size:17px;font-weight:900}
        .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.metric{min-height:82px;padding:11px;border:1px solid #1f1f1f;border-radius:9px;background:#101010}.metric span{color:#707070;font-size:7px;font-weight:900;letter-spacing:.7px}.metric strong{display:block;margin-top:8px;font-size:20px}.metric small{color:#50d582;font-size:7px}
        .dashGrid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-top:12px}.dashCard{min-height:150px;padding:14px;border:1px solid #202020;border-radius:10px;background:#0e0e0e}.dashCard h4{margin:0 0 10px;font-size:10px}.dashCard p{color:#777;font-size:8px;line-height:1.45}.recommend{margin-top:16px;display:inline-block;padding:9px 10px;border-radius:7px;background:#ed2230;color:#fff;font-size:7px;font-weight:900}.chart{height:74px;margin-top:16px;border-bottom:2px solid #ed2230;transform:skewY(-8deg);opacity:.8}
        .phone{position:absolute;width:155px;height:330px;left:2%;bottom:7px;padding:12px;border:2px solid #454545;border-radius:30px;background:#090909;box-shadow:0 18px 55px rgba(0,0,0,.5)}.phoneScreen{height:100%;padding:14px 10px;border-radius:20px;background:#101010}.phoneTitle{font-size:11px;font-weight:900;margin-bottom:14px}.phoneMetric{margin-bottom:10px;padding:10px;border:1px solid #252525;border-radius:8px;font-size:8px;color:#777}.phoneMetric strong{display:block;margin-top:5px;color:#fff;font-size:15px}
        .industryBand{border-bottom:1px solid #1f1f1f;background:#090909}.industryGrid{display:grid;grid-template-columns:180px repeat(9,1fr);min-height:112px;align-items:center}.industryIntro{padding-right:20px;color:#fff;font-size:18px;font-weight:1000;line-height:1.05}.industry{min-height:112px;display:grid;place-items:center;align-content:center;gap:7px;border-left:1px solid #1f1f1f;text-align:center;color:#ddd;font-size:8px;font-weight:900}.industryIcon{color:#ed2230;font-size:24px}
        .results{display:grid;grid-template-columns:1.2fr repeat(4,1fr);border-bottom:1px solid #1f1f1f;background:#060606}.resultIntro,.result{min-height:165px;padding:30px 24px}.resultIntro h2{margin:0;font-size:34px;line-height:.95}.resultIntro h2 span{color:#ed2230}.resultIntro p{color:#828282;font-size:10px;line-height:1.55}.result{border-left:1px solid #272727;text-align:center}.result strong{display:block;color:#ed2230;font-size:32px;margin-bottom:10px}.result span{color:#ddd;font-size:11px;line-height:1.4}
        .featureSection{color:#111;background:#f3f3f1;padding:54px 0}.featureTop{display:grid;grid-template-columns:1.1fr 2.9fr;gap:30px;align-items:start}.featureIntro .eyebrow{color:#ed2230}.featureIntro h2{margin:9px 0 10px;font-size:34px;letter-spacing:-1.5px}.featureIntro p{color:#555;font-size:12px;line-height:1.55}.featureGrid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.featureCard{min-height:190px;padding:20px;background:#fff;border:1px solid #dedede;border-radius:10px}.featureCard .icon{font-size:24px;margin-bottom:14px}.featureCard h3{margin:0 0 9px;font-size:15px}.featureCard p{margin:0;color:#555;font-size:10px;line-height:1.55}
        .managerSection{padding:56px 0;border-bottom:1px solid #202020;background:radial-gradient(circle at 82% 30%,rgba(225,34,45,.12),transparent 28%),#080808}.managerGrid{display:grid;grid-template-columns:1fr 1fr;gap:32px;align-items:center}.managerCopy h2{margin:10px 0 14px;font-size:clamp(42px,4.5vw,68px);line-height:.95;letter-spacing:-3px}.managerCopy h2 span{color:#ed2230}.managerCopy p{color:#8a8a8a;font-size:13px;line-height:1.6;max-width:660px}.managerTasks{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.task{padding:12px;border:1px solid #272727;border-radius:9px;background:#0d0d0d;color:#d0d0d0;font-size:10px}.task span{color:#ed2230;margin-right:7px}.managerCard{padding:26px;border:1px solid #392226;border-radius:16px;background:linear-gradient(145deg,#121212,#090909)}.managerLabel{color:#ed2230;font-size:8px;font-weight:1000;letter-spacing:1.5px}.managerCard h3{margin:8px 0 8px;font-size:30px}.managerCard p{color:#888;font-size:11px;line-height:1.55}.managerActions{display:grid;gap:9px;margin-top:18px}
        .pricing{padding:58px 0;background:#050505}.pricingGrid{display:grid;grid-template-columns:1fr 1fr;gap:28px;align-items:center}.pricing h2{margin:10px 0 10px;font-size:clamp(42px,4.5vw,70px);line-height:.95;letter-spacing:-3px}.pricing h2 span{color:#ed2230}.pricing p{color:#858585;font-size:12px;line-height:1.55}.benefits{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px}.benefit{color:#d5d5d5;font-size:10px}.benefit span{color:#ed2230;margin-right:7px}.priceCard{padding:30px;border:1px solid #392226;border-radius:16px;background:linear-gradient(145deg,#111,#080808)}.priceLabel{color:#777;font-size:8px;font-weight:1000;letter-spacing:1.2px}.money{margin-top:7px;font-size:78px;font-weight:1000;letter-spacing:-5px}.money span{color:#ed2230;font-size:18px;letter-spacing:0}.week{color:#d0d0d0;font-size:11px;margin-bottom:18px}
        .footer{padding:34px 0 50px;border-top:1px solid #1f1f1f;background:#060606}.footerGrid{display:grid;grid-template-columns:1fr 1fr auto;gap:24px;align-items:center}.footerBlock strong{display:block;margin-bottom:5px;font-size:14px}.footerBlock span{color:#777;font-size:10px}
        @media(max-width:1150px){.nav{grid-template-columns:1fr auto}.navLinks{display:none}.hero{grid-template-columns:1fr}.deviceStage{min-height:470px}.industryGrid{grid-template-columns:repeat(5,1fr)}.industryIntro{grid-column:1/-1;padding:20px 0}.results{grid-template-columns:1fr 1fr}.resultIntro{grid-column:1/-1}.featureTop{grid-template-columns:1fr}.featureGrid{grid-template-columns:repeat(3,1fr)}}
        @media(max-width:780px){.shell{width:min(100% - 28px,1500px)}.nav{min-height:74px}.navActions .btnGhost{display:none}.hero{padding-top:34px}.hero h1{letter-spacing:-3px}.deviceStage{min-height:400px}.laptop{width:100%;min-height:360px;padding:10px}.screen{min-height:338px;padding:12px}.metrics{grid-template-columns:1fr 1fr}.dashGrid{grid-template-columns:1fr}.dashCard:nth-child(n+2){display:none}.phone{display:none}.industryGrid{grid-template-columns:repeat(3,1fr)}.results{grid-template-columns:1fr}.resultIntro{grid-column:auto}.result{border-left:0;border-top:1px solid #272727}.featureGrid{grid-template-columns:1fr}.managerGrid,.pricingGrid,.footerGrid{grid-template-columns:1fr}.managerTasks,.benefits{grid-template-columns:1fr}.footerGrid .btn{width:100%}}
      `}</style>

      <header className="shell nav">
        <div className="brand">BUSINESS <span>OS</span><small>GROW EVERY LOCATION.</small></div>
        <nav className="navLinks">
          <button onClick={() => scrollTo("how")}>HOW IT WORKS</button><button onClick={() => scrollTo("features")}>FEATURES</button><button onClick={() => scrollTo("industries")}>INDUSTRIES</button><button onClick={() => scrollTo("manager")}>SUCCESS MANAGER</button><button onClick={() => scrollTo("pricing")}>PRICING</button>
        </nav>
        <div className="navActions"><button className="btn btnGhost" onClick={goLogin}>OWNER LOGIN</button><button className="btn btnRed" onClick={goSignup}>START YOUR BUSINESS OS →</button></div>
      </header>

      <section className="heroWrap" id="how"><div className="shell hero"><div>
        <div className="eyebrow">THE GROWTH OPERATING SYSTEM FOR MAIN STREET AMERICA</div>
        <h1>ONE SYSTEM.<br/>MORE CUSTOMERS.<br/><span>STRONGER BUSINESS.</span></h1>
        <div className="heroLead">Business OS gives local businesses the software, strategy, and hands-on support to attract more customers, build loyalty, and grow more consistently.</div>
        <div className="heroSub">You run the business. We help run the growth engine — with the platform, a clear plan, and a dedicated Marketing Success Manager who helps keep things moving.</div>
        <div className="heroActions"><button className="btn btnRed" onClick={goSignup}>GROW MY BUSINESS →</button><button className="btn btnGhost" onClick={() => scrollTo("features")}>SEE HOW IT WORKS</button></div>
        <div className="proofRow"><div className="proof"><span className="proofIcon">◯</span><span>Dedicated<br/>Success Manager</span></div><div className="proof"><span className="proofIcon">▦</span><span>90-Day<br/>Growth Plan</span></div><div className="proof"><span className="proofIcon">▣</span><span>Client<br/>Command Center</span></div><div className="proof"><span className="proofIcon">▥</span><span>Data-Driven<br/>Results</span></div></div>
      </div><div className="deviceStage"><div className="laptop"><div className="screen"><div className="screenTop"><div className="screenBrand">BUSINESS <span>OS</span></div><div style={{color:"#666",fontSize:8}}>THIS MONTH</div></div><div className="welcome">Welcome back. Here&apos;s what&apos;s happening with your business.</div><div className="metrics"><div className="metric"><span>NEW LEADS</span><strong>248</strong><small>↑ 24%</small></div><div className="metric"><span>MESSAGES</span><strong>143</strong><small>↑ 18%</small></div><div className="metric"><span>APPOINTMENTS</span><strong>32</strong><small>↑ 33%</small></div><div className="metric"><span>REVENUE</span><strong>$18,540</strong><small>↑ 27%</small></div></div><div className="dashGrid"><div className="dashCard"><h4>NEXT BEST MOVE</h4><p>Launch your spring promotion and push it to your customer list.</p><span className="recommend">VIEW RECOMMENDATION</span></div><div className="dashCard"><h4>RECENT ACTIVITY</h4><p>New review received</p><p>New lead captured</p><p>Appointment booked</p></div><div className="dashCard"><h4>PERFORMANCE OVERVIEW</h4><div className="chart"/></div></div></div></div><div className="phone"><div className="phoneScreen"><div className="phoneTitle">Hi, Alex!</div><div className="phoneMetric">NEW LEADS<strong>248</strong></div><div className="phoneMetric">MESSAGES<strong>143</strong></div><div className="phoneMetric">APPOINTMENTS<strong>32</strong></div><div className="phoneMetric">REVENUE<strong>$18,540</strong></div></div></div></div></div></section>

      <section className="industryBand" id="industries"><div className="shell industryGrid"><div className="industryIntro">BUILT FOR<br/>MAIN STREET<br/>BUSINESSES</div>{industries.map(([icon,name])=><div className="industry" key={name}><div className="industryIcon">{icon}</div><div>{name}</div></div>)}</div></section>

      <section className="results"><div className="resultIntro"><h2>REAL BUSINESSES.<br/><span>REAL RESULTS.</span></h2><p>Business OS helps local businesses grow with a proven system and a team that is in your corner.</p></div><div className="result"><strong>+287%</strong><span>Average Increase in<br/><b>New Leads</b></span></div><div className="result"><strong>+41%</strong><span>Average Increase in<br/><b>Customer Retention</b></span></div><div className="result"><strong>+36%</strong><span>Average Increase in<br/><b>Monthly Revenue</b></span></div><div className="result"><strong>98%</strong><span>Client Satisfaction<br/><b>Rate</b></span></div></section>

      <section className="featureSection" id="features"><div className="shell featureTop"><div className="featureIntro"><div className="eyebrow">EVERYTHING YOU NEED TO GROW</div><h2>All-in-One. All for You.</h2><p>Powerful software, expert strategy, and personal support — in one platform built for busy business owners.</p></div><div className="featureGrid">{features.map(([title,text],index)=><article className="featureCard" key={title}><div className="icon">{["📣","☆","💬","▦","▥"][index]}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="managerSection" id="manager"><div className="shell managerGrid"><div className="managerCopy"><div className="eyebrow">YOU GET MORE THAN SOFTWARE</div><h2>YOUR DEDICATED <span>MARKETING SUCCESS MANAGER</span> HELPS MOVE THE WORK FORWARD.</h2><p>You are not buying another dashboard that gets ignored after two weeks. Your Success Manager helps plan campaigns, build offers, review performance, answer questions, and keep your growth plan moving while you stay focused on running the business.</p><div className="managerTasks"><div className="task"><span>✓</span>Strategy + campaign planning</div><div className="task"><span>✓</span>Offer + promotion guidance</div><div className="task"><span>✓</span>Review growth support</div><div className="task"><span>✓</span>Performance check-ins</div></div></div><div className="managerCard"><div className="managerLabel">YOUR GROWTH PARTNER</div><h3>Help is inside the platform.</h3><p>Message your Success Manager directly from your Command Center or book a strategy call when you want to work through the next move together.</p><div className="managerActions"><button className="btn btnRed" onClick={goSignup}>START WITH BUSINESS OS →</button><button className="btn btnGhost" onClick={() => scrollTo("pricing")}>SEE PRICING</button></div></div></div></section>

      <section className="pricing" id="pricing"><div className="shell pricingGrid"><div><div className="eyebrow">ONE SIMPLE PRICE. FULL FIREPOWER.</div><h2>SOFTWARE + STRATEGY + <span>REAL HUMAN SUPPORT.</span></h2><p>One straightforward system for local businesses that want stronger customer growth without stitching together a dozen disconnected tools.</p><div className="benefits">{benefits.map(b=><div className="benefit" key={b}><span>✓</span>{b}</div>)}</div></div><div className="priceCard"><div className="priceLabel">ONE SIMPLE MONTHLY PRICE</div><div className="money">$375 <span>/ MONTH</span></div><div className="week">ABOUT $87 / WEEK</div><button className="btn btnRed" onClick={goSignup}>START YOUR BUSINESS OS →</button></div></div></section>

      <footer className="footer"><div className="shell footerGrid"><div className="footerBlock"><strong>Your Dedicated Success Manager</strong><span>Strategy. Support. Growth. You&apos;re never alone.</span></div><div className="footerBlock"><strong>Onboarding + 90-Day Plan</strong><span>We help you hit the ground running with a clear growth plan.</span></div><button className="btn btnRed" onClick={goSignup}>START YOUR BUSINESS OS →</button></div></footer>
    </main>
  );
}
